apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-iso-dv
spec:
  source:
    http:
      url: "https://releases.ubuntu.com/22.04/ubuntu-22.04-live-server-amd64.iso"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 5Gi
    storageClassName: ibmc-vpc-block-10iops-tier
